# Directories 
data_dir: ../../../../../groups/kempter/chen/data
save_dir: .


# Model Hyperparameters
norm_type: bn
nepoch: 10
image_size: 128
ch_multi: 32
num_res_blocks: 1
gpu_index: 1
latent_channels: 128
save_interval: 3000
block_widths: 1, 2, 4, 8
lr: 0.0003
kl_scale: 0.0001
deep_model: 0

# Configure which variables to set as treatment and which as covariates
treatment:
  Young: 39  # Add index for treatment variable corresponding to CelebA labels

model_labels:
  5_o_Clock_Shadow: 0
  # Arched_Eyebrows: 1
  # Attractive: 2
  # Bags_Under_Eyes: 3
  Bald: 4
  Bangs: 5
  Big_Lips: 6
  Big_Nose: 7
  Black_Hair: 8
  Blond_Hair: 9
  # Blurry: 10
  Brown_Hair: 11
  Bushy_Eyebrows: 12
  # Chubby: 13
  Double_Chin: 14
  Eyeglasses: 15
  Goatee: 16
  Gray_Hair: 17
  Heavy_Makeup: 18
  High_Cheekbones: 19
  Male: 20
  Mouth_Slightly_Open: 21
  Mustache: 22
  Narrow_Eyes: 23
  No_Beard: 24
  Oval_Face: 25
  Pale_Skin: 26
  Pointy_Nose: 27
  Receding_Hairline: 28
  Rosy_Cheeks: 29
  Sideburns: 30
  Smiling: 31
  Straight_Hair: 32
  Wavy_Hair: 33
  Wearing_Earrings: 34
  Wearing_Hat: 35
  Wearing_Lipstick: 36
  # Wearing_Necklace: 37
  # Wearing_Necktie: 38
  # Young: 39



####################
# labels:
#   5_o_Clock_Shadow: 0
#   Arched_Eyebrows: 1
#   Attractive: 2
#   Bags_Under_Eyes: 3
#   Bald: 4
#   Bangs: 5
#   Big_Lips: 6
#   Big_Nose: 7
#   Black_Hair: 8
#   Blond_Hair: 9
#   Blurry: 10
#   Brown_Hair: 11
#   Bushy_Eyebrows: 12
#   Chubby: 13
#   Double_Chin: 14
#   Eyeglasses: 15
#   Goatee: 16
#   Gray_Hair: 17
#   Heavy_Makeup: 18
#   High_Cheekbones: 19
#   Male: 20
#   Mouth_Slightly_Open: 21
#   Mustache: 22
#   Narrow_Eyes: 23
#   No_Beard: 24
#   Oval_Face: 25
#   Pale_Skin: 26
#   Pointy_Nose: 27
#   Receding_Hairline: 28
#   Rosy_Cheeks: 29
#   Sideburns: 30
#   Smiling: 31
#   Straight_Hair: 32
#   Wavy_Hair: 33
#   Wearing_Earrings: 34
#   Wearing_Hat: 35
#   Wearing_Lipstick: 36
#   Wearing_Necklace: 37
#   Wearing_Necktie: 38
#   Young: 39


